### ISSUE TITLE
Library has no soname version

### ISSUE THREAD

**Issue by tim77** [WayfireWM/wf-config#12]
Hello. Trying to package and push **wayfire** in official Fedora repos but there some things which require by Fedora guidelines, so maybe we can fix this:
https://docs.fedoraproject.org/en-US/packaging-guidelines/#_downstream_so_name_versioning

Here is review request:
https://bugzilla.redhat.com/show_bug.cgi?id=1756496#c1

**Comment by ammen99** [comment]
That's cool, thanks for the effort. I'll try to add this ASAP.
