### ISSUE TITLE
generated wf-config.pc file uses "Unknown version comparison operator"

### ISSUE THREAD

**Issue by Wychmire** [WayfireWM/wf-config#14]
wf-shell fails to compile because pkg-config's wf-config.pc uses `==` instead of `=`:
```
Unknown version comparison operator '==' after package name 'wlroots' in file '/usr/lib/pkgconfig/wf-config.pc'
```
After editing `/usr/lib/pkgconfig/wf-config.pc` to use `=` instead of `==` compiling moves on. Valid comparison operators are =, <, >, <= or >=.

**Comment by ammen99** [comment]
What meson version are you using?

**Comment by Wychmire** [comment]
0.51.2:
```
$ meson --version
0.51.2
```

**Comment by ammen99** [comment]
Do you have a reference for valid comparators?

**Comment by ammen99** [comment]
This is strange because my meson is only `0.50.1` and I get no such error. What is your version of pkg-config?

**Comment by Wychmire** [comment]
I grabbed the ones I mentioned from https://people.freedesktop.org/~dbn/pkg-config-guide.html#concepts

pkg-config is at 0.29.2

**Comment by ammen99** [comment]
My pkg-config is 1.6.1 and it supports ==, however it was just pointed out to me we also want to support higher wlroots versions so I'll update the two package tarballs.

**Comment by Wychmire** [comment]
pkg-config(1) also mentions the valid comparators under METADATA FILE SYNTAX:

```
       Requires:
              This is a comma-separated list of packages that are required by
              your package. Flags from dependent packages will be merged in to
              the flags reported for your package. Optionally, you can specify
              the version of the required package (using the operators =, <,
              >, >=, <=); specifying a version allows pkg-config to perform
              extra sanity checks. You may only mention the same package one
              time on the Requires: line. If the version of a package is
              unspecified, any version will be used with no checking.
```

Maybe an older version supported `==`?

**Comment by ammen99** [comment]
I am not sure. I just updated the 0.3 release tarball and the master branch to use >=. Hope it works now :)
