### ISSUE TITLE
Wayfire crashes if plugins option is not defined in core section of config file

### ISSUE THREAD

**Issue by soreau** [WayfireWM/wf-config#19]
what():  No such option: core/plugins

This doesn't happen with any option that is defined in the xml files, only with ones that aren't, such as this one.

**Comment by ammen99** [comment]
This is the expected behavior, we have simply missed this option in the config file (note this happens because of missing XMLs)

**Comment by soreau** [comment]
Wait, I thought missing options were a hard error in wf-config.. is this no longer the case?

**Comment by ammen99** [comment]
Yes, exactly, and this is such an error. However keep in mind you can have options with no XMLs - for example, output config options, because you don't know their names in advance. In that case however, one should not use option wrapper.

**Comment by ammen99** [comment]
Hm, you're right. We just should assert that there is a XML node for each option from option wrapper

**Comment by soreau** [comment]
Oh right, this is what happens when an option isn't found in neither the xml nor the config file.

**Comment by ammen99** [comment]
Changed my mind again, it is perfectly fine to have option_wrapper for options which do not come from the XML files (if for example options are programatically added)
