### ISSUE TITLE
Support lists in /etc/wayfire/defaults.ini

### ISSUE THREAD

**Issue by AdrianVovk** [WayfireWM/wf-config#30]
Title explains it. Right now, lists are ignored from that config file

Also, there needs to be a way for items to be added to the list in ~/.config/wayfire.ini without disrupting the items in /etc (for example, I can have a default list of plugins in /etc and then optionally load in stuff like cube in ~)

**Comment by ammen99** [comment]
> Title explains it. Right now, lists are ignored from that config file
> 
> Also, there needs to be a way for items to be added to the list in ~/.config/wayfire.ini without disrupting the items in /etc (for example, I can have a default list of plugins in /etc and then optionally load in stuff like cube in ~)

I don't like this particular thing, goes against wayfire's philosophy. I think it would be better to have two separate lists of plugins (`plugins_system` and `plugins_user`) on the Wayfire side. Both will be overwritable by users, but for ex. you can overwrite the one and let users use the other. That should be enough for you I hope?

List support in general are useful, that will definitely be implemented eventually.

**Comment by ammen99** [comment]
> > Title explains it. Right now, lists are ignored from that config file
> > Also, there needs to be a way for items to be added to the list in ~/.config/wayfire.ini without disrupting the items in /etc (for example, I can have a default list of plugins in /etc and then optionally load in stuff like cube in ~)
> 
> I don't like this particular thing, goes against wayfire's philosophy. I think it would be better to have two separate lists of plugins (`plugins_system` and `plugins_user`) on the Wayfire side. Both will be overwritable by users, but for ex. you can set the one globally and let users use the other. That should be enough for you I hope?
> 
> List support in general are useful, that will definitely be implemented eventually.

**Comment by AdrianVovk** [comment]
@ammen99 Yeah that's the solution I mentioned in IRC. As long as users won't be nuking my config unless they really mean to I'm happy with it 👍

Maybe the options should be `plugins` and `global_plugins` or `dist_plugins`?

**Comment by AdrianVovk** [comment]
Just a note I know plugins isn't a real "list" type right now, but stuff like autostart and command should behave the same way (I can set a global autostart script, and users can add things to their own autostart, and I guess if they want they can override mine)

**Comment by ammen99** [comment]
For future reference: I believe in fact the best way for this to happen is simply a custom config backend for Wayfire, which can take the options from whichever files it needs to.
