### ISSUE TITLE
[switcher] Plugin always turned off in GUI

### ISSUE THREAD

**Issue by nwg-piotr** [WayfireWM/wf-config#32]
Even if I check the Switcher check box (or "Use This Plugin" in plugin setting), it remains turned off, as if settings had not been saved. Adding `switcher` to `plugins =` in wayfire.ini works as expected.

**Comment by soreau** [comment]
The only thing wcm does to save settings is write the config file. If it's not doing this, it's a wcm bug. I'd check permissions on the config file.

**Comment by nwg-piotr** [comment]
Other settings are being saved correctly.

**Comment by soreau** [comment]
Works fine for me here, not sure what could be going wrong.

**Comment by nwg-piotr** [comment]
Not a big issue, but worth of diagnosing. I'm on a fresh install from the master branch.

**Comment by soreau** [comment]
When you enable Switcher in wcm, it doesn't write 'switcher' to the plugin list in the config file? And you're not confusing Fast Switcher with Switcher, right?

It might clear things up if you `grep -in switch ~/.config/wayfire.ini` before and after enabling/disabling the checkbox in wcm. Also, presumably you are using the git version of wcm?

**Comment by nwg-piotr** [comment]
I've just enabled Switcher in wfc, and opened the wayfire.ini file:

![image](https://user-images.githubusercontent.com/20579136/96339872-886ec900-1097-11eb-8853-3dfddefb88ce.png)

**Comment by soreau** [comment]
I see that it has `fast-` in the plugin list which seems odd. Are you using wayfire -c or --config option to specify a config file by chance?

**Comment by nwg-piotr** [comment]
I don't. I also have no idea what the `fast-` may mean. My config file derives from the very first one.

**Comment by soreau** [comment]
Ah, it is a wcm bug. I can reproduce it now. It is because fast-switcher is enabled, then when switcher is disabled it looks for the first instance of 'switcher' to eliminate from the plugin string. This leaves `fast-` so it needs to be a bit smarter. Will send a patch.

**Comment by nwg-piotr** [comment]
I expected something like this.

**Comment by soreau** [comment]
@nwg-piotr [This](https://github.com/WayfireWM/wcm/commit/13b8bc6c922ea248ea97e235e5a0b827fdc3a591) should fix it.
