### ISSUE TITLE
Run-time dependency glm found: NO (tried pkgconfig)

### ISSUE THREAD

**Issue by tim77** [WayfireWM/wf-config#39]
Pkgconfig support is no longer supported in `glm` upstream and not shipped in v0.9.9.8 for some reason. `wf-config` should not require pkgconfig version of `glm` during build. Same applies for `wayfire`.

**Comment by AdrianVovk** [comment]
Distros package glm.pc now, and I'm pretty sure many other packages depend on the pkgconfig file. No idea why upstream would get rid of it. But anyway, here's what the file can look like: [Source](https://gitlab.com/carbonOS/build-meta/-/blob/master/files/glm.pc) and [sed script](https://gitlab.com/carbonOS/build-meta/-/blob/master/elements/pkgs/glm.bst#L19). You can also just drop this file anywhere and run meson with PKG_CONFIG_PATH set.

**Comment by AdrianVovk** [comment]
Distros package glm.pc now, and I'm pretty sure many other packages depend on the pkgconfig file. No idea why upstream would get rid of it. But anyway, here's what the file can look like: [Source](https://gitlab.com/carbonOS/build-meta/-/blob/master/files/glm.pc) and [sed script](https://gitlab.com/carbonOS/build-meta/-/blob/master/elements/pkgs/glm.bst#L19). There's also this:

**Comment by alebastr** [comment]
`glm` now ships only cmake config and meson is able to resolve dependencies using it as a fallback. However that requires cmake to be installed during build time.
In the case of @tim77's Fedora packages build requirements should be updated to include `cmake` and `cmake(glm)`.

**Comment by tim77** [comment]
> packages build requirements should be updated to include cmake and cmake(glm)

Indeed. @AdrianVovk @alebastr thanks a lot. Was rushed a little bit and was really surprised with this `glm` change.

**Comment by soreau** [comment]
Maybe we could install glm headers as a subproject.

**Comment by ammen99** [comment]
> Maybe we could install glm headers as a subproject.

GLM is a widely used and packaged library, I don't see any gain in using it as a subproject ...

**Comment by soreau** [comment]
> > Maybe we could install glm headers as a subproject.
> 
> GLM is a widely used and packaged library, I don't see any gain in using it as a subproject ...

The gain being that meson could have a dependency object without relying on pkgconfig or cmake.

**Comment by AdrianVovk** [comment]
Everything else depends on pkgconfig so why can't glm?
