### ISSUE TITLE
changing options resets wayfire scaling

### ISSUE THREAD

**Issue by MrSwedish** [WayfireWM/wf-config#47]
I have to restart wayfire

**Comment by MrSwedish** [comment]
ahh you guys added configure outputs, nice taht fixed it

**Comment by MrSwedish** [comment]
it didn't

**Comment by ammen99** [comment]
How are you setting output scale?

**Comment by ammen99** [comment]
As discussed on IRC, this stems from an invalid configuration. Instead of using:

```ini
[output]
scale = 2.0
```
we should use:

```ini
[output:HDMI-A-2] # or any other connector name
scale = 2.0
```
