### ISSUE TITLE
Please include a license file

### ISSUE THREAD

**Issue by maxice8** [WayfireWM/wf-config#8]
Trying to get this packaged on Void Linux and we know the license is MIT but there is no license file with your copyright we can bring with the package.

This blocks [inclusion](https://github.com/void-linux/void-packages/pull/8474) into Void Linux

**Comment by ammen99** [comment]
Okay, done. Thanks for packaging!

**Comment by maxice8** [comment]
On Mon, Feb 11, 2019 at 07:43:14PM +0000, Ilia Bozhinov wrote:
> Okay, done. Thanks for packaging!
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/WayfireWM/wf-config/issues/8#issuecomment-462466495

Thanks for the quick response, i have instructed the Void Linux contributor trying to package it on how to proceed.
